# Generated by Django 2.2.10 on 2020-02-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penaltylogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='player',
            field=models.IntegerField(),
        ),
    ]
